site_name: Dev Notes
site_url: https://lcsgborges.github.io/dev-notes/
repo_name: dev-notes
repo_url: https://github.com/lcsgborges/dev-notes
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  language: pt-BR
  palette:
    scheme: default
    primary: blue grey
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.top
    - content.code.copy
nav:
  - Início: index.md
  - Fundamentos da Computação:
      - Fundamentos de Rede:
          - Primeiros passos: fundamentos/redes/introducao.md
          - Camadas de rede: fundamentos/redes/camadas.md
  - Linguagens de Programação:
      - C:
          - Ponteiros: c/ponteiros.md
          - Arquivos em C: c/arquivos.md
          - Processos e IPC:
              - Introdução: c/processos/introducao.md
              - Memória de processo: c/processos/memoria.md
              - Descritores de arquivo: c/processos/fd.md
              - Processos com fork: c/processos/fork.md
              - Sinais: c/processos/signals.md
              - Pipes: c/processos/pipes.md
              - FIFOs: c/processos/fifos.md
              - Message Queues: c/processos/message_queues.md
              - Shared Memory: c/processos/shared_memory.md
              - Unix Domain Sockets: c/processos/unix_domain_sockets.md
              - TCP Sockets: c/processos/tcp_sockets.md
          - Threads: c/threads.md
          - OpenMP: c/openmp.md
      - Go:
          - Primeiros passos: go/go.md
          - Exercícios: go/exercicios_basicos_go.md
      - Java:
          - Primeiros passos: java/introducao/introducao.md
          - Orientação a objetos:
              - Orientação a objetos I: java/orientacao-a-objetos/poo1.md
          - Estruturas de dados:
              - Arrays e listas: java/estrutura-de-dados/arrays_e_listas.md
          - Exercícios:
              - Primeiros passos: java/introducao/exercicios_basicos.md
              - Orientação a objetos I: java/orientacao-a-objetos/exercicios_poo1.md
      - Python:
          - Alembic: python/alembic.md
          - Pillow: python/pillow.md
          - SQLAlchemy: python/sqlalchemy.md
          - Anotações de tipo: python/types-hints-py.md
  - DevOps:
      - Docker: devops/docker.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
